# Generated by Django 3.2 on 2021-04-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('asked_question', models.BooleanField()),
                ('multiple_questions', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StackApp.user')),
            ],
        ),
    ]
